### ISSUE TITLE
guid displaying in venafi policy tree

### ISSUE THREAD

**Issue by RUONES** [Venafi/vault-pki-monitor-venafi#1]
Not too big of an issue but the object guid displays in the Venafi policy tree - anyway to port over the certificate object name as a display name?

Also, would this work for PKI engines created outside the Venafi plug-in? Meaning, enabling the plug-in with the ability to import signed certificates for other PKI engines running in Vault?

**Comment by arykalin** [comment]
Hi
1. I'll look at it, can't say now.
2. Unfortunately not. Certificates are adding to import queue only when they created, there is no way to import already existing certificates. But I'm thinking about a way of importing already existing certificates, something like sync operation.

**Comment by RUONES** [comment]
thanks. awesome work btw - the sync option would be great for enterprises looking to leverage vault but maintain some sort of visibility to certs issued - maybe even go as far as porting over the private key for issued certs through the venafi import.
