### ISSUE TITLE
Upstream functionality

### ISSUE THREAD

**Issue by jefferai** [Venafi/vault-pki-monitor-venafi#2]
Is there a reason to fork the entire plugin rather than see if the functionality can be upstreamed?

**Comment by jefferai** [comment]
That sounds good, although if you are planning to upstream it I'd suggest working on the design with us ahead of finalizing it yourself. That way if there are concerns that need to be addressed, you don't need to either maintain a fork, or do a lot of rewriting on your end.

**Comment by tr1ck3r** [comment]
I'm currently coordinating with Marshall Copeland on the next steps for upstreaming this project into Vault.
