### ISSUE TITLE
Add Sensitive DisplayAttribute to tpp_password and apikey

### ISSUE THREAD

**Issue by mbrancato** [Venafi/vault-pki-monitor-venafi#25]
The plugin config is not a secure storage mechanism. Where the Venafi plugin is capturing the TPP password or API Key in the config, it is important to make these write-only.

[Example implementation](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/6a4ef1ab96ad21da959159d3bb95c31502b85de4/path_config.go#L40-L42)

**Comment by mbrancato** [comment]
It looks like this may require changing this function as well to not return the data.
https://github.com/Venafi/vault-pki-monitor-venafi/blob/f85fe8d8c108a61a57d1862a9411cc139e8e8901/plugin/pki/path_roles.go#L807

**Comment by mr-tron** [comment]
First  we need update vault api to version 1.3.0

**Comment by mbrancato** [comment]
Can't this be completed by just omitting those fields in the `ToResponseData()` method?
