### ISSUE TITLE
SHA256SUM files no longer provided (V0.6)

### ISSUE THREAD

**Issue by cdmadrigal** [Venafi/vault-pki-monitor-venafi#38]
**PROBLEM SUMMARY**
V0.6 release of the plugin no longer includes the SHA256SUM files as assets for the release. Either add the files again to match the instructions or edit the README file to disregard the need to check for the file.

**STEPS TO REPRODUCE**
Release files don't have SHA256SUM files. Try running a curl for the latest version and it will fail.

**EXPECTED RESULTS**
SHA256SUM file gets downloaded like in previous versions.

**ACTUAL RESULTS**
File no longer exists so download fails. This means if you choose to initiate this plugin in your Hashicorp Vault, it would have to be without authenticating the SHA signature.

**ENVIRONMENT DETAILS**
Amazon Linux 2

**COMMENTS/WORKAROUNDS**
Workaround: Use a previous version (V0.5.5 or earlier).

**Comment by tr1ck3r** [comment]
Thank you for catching this @cdmadrigal.  We've moved away from releasing SHA256 checksum files for every binary and instead list the SHA256 checksums for each zip package in the release notes.  I've updated the [README](../blob/master/README.md) to reflect the new procedure.  Please review and let me know if I've addressed your concerns.

**Comment by cdmadrigal** [comment]
README changes look good. Thanks!
